version: 2

defaults:
  workspace_root: &workspace_root
    ~/csw-client

  nodejs_container: &nodejs_container
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10-stretch

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-csw-client-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v1-csw-client-node-master-{{ checksum "yarn.lock" }}
        - v1-csw-client-node-master-

jobs:
  checkout:
    <<: *nodejs_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - v1-csw-client-yarn-{{ checksum "yarn.lock" }}
            - v1-csw-client-yarn-

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile

      - save_cache:
          name: Save yarn cache
          key: v1-csw-client-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/

      - save_cache:
          name: Save node_modules cache
          key: v1-csw-client-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  lint:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Lint
          command: yarn lint

  test:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Upload code coverage to codecov
          command: yarn codecov

workflows:
  version: 2

  push:
    jobs:
      - checkout

      - install:
          requires:
            - checkout

      - lint:
          requires:
            - install

      - test:
          requires:
            - install
